# Generated by Django 3.0.3 on 2020-02-06 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectviewed',
            name='ip_address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
